
tag * remove is_full
tag * remove is_full_max
tag * remove is_low
tag * remove is_sneaking
tag * remove is_shifting
tag * remove is_walking
tag * remove is_sprinting
tag * remove is_swimming
tag * remove is_afking
tag * remove is_moving
tag * remove is_falling
tag * remove is_using_item
tag * remove is_holding_item
tag * remove is_alive
tag * remove is_dead
tag * remove is_on_ground
tag * remove is_grounded
tag * remove is_burning
tag * remove is_in_water
tag * remove is_in_air
tag * remove is_sleeping
tag * remove has_health_1
tag * remove has_health_2
tag * remove has_health_3
tag * remove has_health_4
tag * remove has_health_5
tag * remove has_health_6
tag * remove has_health_7
tag * remove has_health_8
tag * remove has_health_9
tag * remove has_health_10
tag * remove has_health_11
tag * remove has_health_12
tag * remove has_health_13
tag * remove has_health_14
tag * remove has_health_15
tag * remove has_health_16
tag * remove has_health_17
tag * remove has_health_18
tag * remove has_health_19
tag * remove has_health_20
tag * remove has_health_21
tag * remove has_health_22
tag * remove has_health_23
tag * remove has_health_24

tag @a remove is_full
tag @a remove is_full_max
tag @a remove is_low
tag @a remove is_sneaking
tag @a remove is_shifting
tag @a remove is_walking
tag @a remove is_sprinting
tag @a remove is_swimming
tag @a remove is_afking
tag @a remove is_moving
tag @a remove is_falling
tag @a remove is_using_item
tag @a remove is_holding_item
tag @a remove is_alive
tag @a remove is_dead
tag @a remove is_on_ground
tag @a remove is_grounded
tag @a remove is_burning
tag @a remove is_in_water
tag @a remove is_in_air
tag @a remove is_sleeping
tag @a remove has_health_1
tag @a remove has_health_2
tag @a remove has_health_3
tag @a remove has_health_4
tag @a remove has_health_5
tag @a remove has_health_6
tag @a remove has_health_7
tag @a remove has_health_8
tag @a remove has_health_9
tag @a remove has_health_10
tag @a remove has_health_11
tag @a remove has_health_12
tag @a remove has_health_13
tag @a remove has_health_14
tag @a remove has_health_15
tag @a remove has_health_16
tag @a remove has_health_17
tag @a remove has_health_18
tag @a remove has_health_19
tag @a remove has_health_20
tag @a remove has_health_21
tag @a remove has_health_22
tag @a remove has_health_23
tag @a remove has_health_24

tellraw @s {"rawtext":[{"text":"§r\n§f<§bTamamo Library§f> §f输入 §7/function removed §f重置玩家所有标签.\n§r"}]}